---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool:latest
        ports:
        - containerPort: 80
          name: http-port
      initContainers:
      - name: delay
      # the version was picked to avoid problems with nslookup that can occure in versions >= 1.28.4
        image: busybox:1.28.3
        command: ['sh', '-c', 'while true; do sleep 1; if nslookup backend-svc; then exit 0; fi; done; exit 1']

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: app
spec:
  ports:
    - name: multitool-back
      port: 8081
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: backend