---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool:latest
        ports:
        - containerPort: 80
      initContainers:
      - name: delay
      # the version was picked to avoid problems with nslookup that can occure in versions >= 1.28.4
        image: busybox:1.28.3
        command: ['sh', '-c', 'while true; do sleep 1; if nslookup frontend-svc; then exit 0; fi; done; exit 1']


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  ports:
    - name: multitool-front
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: frontend