apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: task24
  name: pod-logs-desc
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["logs", "describe", "list", "get"]