apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
    - name: multitool-http
      port: 1180
      targetPort: http-port
      protocol: TCP
    - name: multitool-https
      port: 11443
      targetPort: https-port
      protocol: TCP
  type: ClusterIP
  selector:
    app: netology