apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netology
  template:
    metadata:
      labels:
        app: netology
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool
        image: praqma/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http-port
      initContainers:
      - name: delay
      # the version was picked to avoid problems with nslookup that can occure in versions >= 1.28.4
        image: busybox:1.28.3
        command: ['sh', '-c', 'while true; do sleep 1; if nslookup netology-svc; then exit 0; fi; done; exit 1']