apiVersion: v1
kind: Service
metadata:
  name: netology-svc-external
spec:
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
      protocol: TCP
    - name: multitool-http
      port: 9002
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: netology