resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    node0 ansible_host=${yandex_compute_instance.master01.network_interface.0.nat_ip_address} ansible_user=ubuntu ip=${yandex_compute_instance.master01.network_interface.0.ip_address}
    node1 ansible_host=${yandex_compute_instance.worker01.network_interface.0.nat_ip_address} ansible_user=ubuntu ip=${yandex_compute_instance.worker01.network_interface.0.ip_address}
    node2 ansible_host=${yandex_compute_instance.worker02.network_interface.0.nat_ip_address} ansible_user=ubuntu ip=${yandex_compute_instance.worker02.network_interface.0.ip_address}
    node3 ansible_host=${yandex_compute_instance.worker03.network_interface.0.nat_ip_address} ansible_user=ubuntu ip=${yandex_compute_instance.worker03.network_interface.0.ip_address}
    node4 ansible_host=${yandex_compute_instance.worker04.network_interface.0.nat_ip_address} ansible_user=ubuntu ip=${yandex_compute_instance.worker04.network_interface.0.ip_address}

    [kube_control_plane]
    node0

    [etcd]
    node0

    [kube_node]
    node1
    node2
    node3
    node4

    [k8s_cluster:children]
    kube_node
    kube_control_plane

    DOC
  filename = "../kubespray/inventory/sample/prod.yml"

  depends_on = [
    yandex_compute_instance.master01,
    yandex_compute_instance.worker01,
    yandex_compute_instance.worker02,
    yandex_compute_instance.worker03,
    yandex_compute_instance.worker03
  ]
}
