apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"web-consumer","namespace":"web"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"web-consumer"}},"template":{"metadata":{"labels":{"app":"web-consumer"}},"spec":{"containers":[{"command":["sh","-c","while true; do curl auth-db; sleep 5; done"],"image":"radial/busyboxplus:curl","name":"busybox"}]}}}}
  creationTimestamp: "2023-10-08T10:53:44Z"
  generation: 1
  name: web-consumer
  namespace: web
  resourceVersion: "535802"
  uid: eeedfff4-84c7-42d2-b8c2-e48728a1d0ce
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-consumer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-consumer
    spec:
      containers:
      - command:
        - sh
        - -c
        - while true; do curl auth-db; sleep 5; done
        image: radial/busyboxplus:curl
        imagePullPolicy: IfNotPresent
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-10-08T10:53:50Z"
    lastUpdateTime: "2023-10-08T10:53:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-10-08T10:53:44Z"
    lastUpdateTime: "2023-10-08T10:53:50Z"
    message: ReplicaSet "web-consumer-84fc79d94d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
